openapi: 3.0.3
info:
  title: Comercio API
  description: Información del Comercio
  version: 1.0.0
  contact:
    name: Antonio Diaz
    email: adr343@gmail.com
servers:
  - url: https://localhost:8080/comercio
    description: Servidor de pruebas
tags:
  - name: Prices
    description: Endpoints relacionados con los precios de los productos
paths:
  /price/{productId}/{brandId}:
    get:
      tags:
        - Prices
      summary: Obtener el precio del producto buscando por ID de empresa, producto y fecha de aplicacion.
      description: Obtener el precio del producto buscando por ID de empresa, producto y fecha de aplicacion.
      operationId: getPriceInfoByProduct
      parameters:
        - in: path
          name: brandId
          description: Shop id
          required: true
          schema:
            type: integer
          example: 1
        - in: path
          name: productId
          description: Product id
          required: true
          schema:
            type: integer
          example: 1565
        - in: query
          name: applicationDate
          description: Application date
          required: true
          schema:
            type: string
            format: LocalDateTime
          example: '2023-05-01T14:30:00'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceDTO'
              example:
                brandId: '1'
                productId: '1565'
                consultationDate: '2023-05-01T14:30:00Z'
                precio: 19.99
                curr: EUR
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                message: "Invalid parameter type"
                details: "The date format should be 'yyyy-MM-dd'T'HH:mm:ss'"
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                message: "Recurso no encontrado"
                details: "Recurso no encontrado"
        '204':
          description: No content
        '422':
          description: Unprocessable Content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                message: "Database is not accessible"
                details: "There was an issue connecting to the database"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                message: "Internal Server Error"
                details: "An unexpected error occurred"

components:
  schemas:
    PriceDTO:
      type: object
      properties:
        brandId:
          description: company id
          type: integer
          example: 1
        productId:
          description: product id
          type: integer
          example: 1567
        startDate:
          description: start application date
          type: string
          format: LocalDateTime
          example: '2023-05-01T14:30:00'
        endDate:
          description: end application date
          type: string
          format: LocalDateTime
          example: '2023-05-01T14:30:00'
        price:
          description: price
          type: number
          example: 19.99
        currency:
          description: currency
          type: string
          example: EUR
    ErrorDTO:
      type: object
      properties:
        message:
          description: Breve descripción del error
          type: string
          example: "Invalid parameter type"
        details:
          description: Detalles adicionales sobre el error
          type: string
          example: "The date format should be 'yyyy-MM-dd'T'HH:mm:ss'"