server:
  error:
    include-stacktrace: never
  servlet:
    context-path: /comercio

spring:
  application:
    name: comercio
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none  # Usamos schema.sql para crear la tabla, por lo que no necesitamos que Hibernate cree las tablas
    sql:
      init:
        mode: embedded  # Solo ejecutar SQL init cuando se use H2 u otra BD embebida
    open-in-view: false # Buena práctica deshabilitar Open Session in View
  h2:
    console:
      enabled: false
  doc:
    api-docs:
      path: /v3/api-docs  # Ruta de la especificación OpenAPI
    swagger-ui:
      path: /swagger-ui  # Ruta del Swagger UI
